"""Build Foundry-ready sanitized measurement data from approved provider rows.

Input is the private import artifact generated by ``scripts/import_candidate_signals.py``.
Output is a public-safe CSV/JSON bundle under ``out/foundry_live_measurement``:

* no raw provider envelope
* no API key/JWT
* no raw email/password/cookie/token
* stable hashed object primary keys for Foundry object/link datasets
"""

from __future__ import annotations

import csv
import hashlib
import json
import re
from collections import Counter
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[1]
INPUT_JSON = REPO_ROOT / "out" / "private_candidate_import.json"
OUT_DIR = REPO_ROOT / "out" / "foundry_live_measurement"
OUT_JSON = OUT_DIR / "measurement.json"
OUT_MD = OUT_DIR / "measurement.md"
OUT_HTML = OUT_DIR / "measurement.html"
PUBLIC_HTML = REPO_ROOT / "out" / "foundry_live_measurement.html"

EMAIL_RE = re.compile(r"[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}")
FORBIDDEN_RE = re.compile(
    r"(Bearer\s+[A-Za-z0-9._-]+|eyJ[A-Za-z0-9._-]+|STEALTHMOLE_(?:ACCESS|SECRET)_KEY)",
    re.IGNORECASE,
)


def _read_json(path: Path) -> dict[str, Any]:
    data = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(data, dict):
        raise ValueError(f"{path} must contain a JSON object")
    return data


def _hash_text(value: Any) -> str:
    return hashlib.sha256(str(value).encode("utf-8")).hexdigest()[:16]


def _clean_domain(value: Any) -> str:
    text = str(value or "unknown.invalid").strip().lower()
    text = text.removeprefix("https://").removeprefix("http://")
    text = text.split("/", 1)[0].split(":", 1)[0]
    text = text.lstrip("*@").lstrip("*.").strip(".")
    return text or "unknown.invalid"


def _iso(value: Any) -> str:
    if value is None or value == "":
        return ""
    if isinstance(value, (int, float)):
        return datetime.fromtimestamp(value, tz=timezone.utc).isoformat()
    return str(value)


def _write_csv(name: str, rows: list[dict[str, Any]]) -> None:
    if not rows:
        return
    path = OUT_DIR / name
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(rows[0].keys()), lineterminator="\n")
        writer.writeheader()
        writer.writerows(rows)


def _dedupe(rows: list[dict[str, Any]], key: str) -> list[dict[str, Any]]:
    seen: dict[Any, dict[str, Any]] = {}
    for row in rows:
        seen.setdefault(row[key], row)
    return list(seen.values())


def build(data: dict[str, Any]) -> dict[str, Any]:
    exposures = data.get("normalized_exposures") or []
    if not isinstance(exposures, list):
        raise ValueError("normalized_exposures must be a list")

    suppliers: list[dict[str, Any]] = []
    programs: list[dict[str, Any]] = []
    domains: list[dict[str, Any]] = []
    identities: list[dict[str, Any]] = []
    credential_exposures: list[dict[str, Any]] = []
    infected_devices: list[dict[str, Any]] = []
    threat_sources: list[dict[str, Any]] = []
    link_owns: list[dict[str, Any]] = []
    link_belongs_to: list[dict[str, Any]] = []
    link_of: list[dict[str, Any]] = []
    link_targets: list[dict[str, Any]] = []
    link_sourced_from: list[dict[str, Any]] = []
    link_leaked: list[dict[str, Any]] = []
    link_compromises: list[dict[str, Any]] = []

    module_counts: Counter[str] = Counter()
    active_count = 0
    host_counts: Counter[str] = Counter()

    for row in exposures:
        if not isinstance(row, dict):
            continue
        module = str(row.get("module") or "unknown").lower()
        source_hash = str(row.get("source_ref_hash") or _hash_text(row.get("id") or module))
        scope = row.get("scope") or {}
        if not isinstance(scope, dict):
            scope = {}
        device = row.get("device") or {}
        if not isinstance(device, dict):
            device = {}
        secret = row.get("secret") or {}
        if not isinstance(secret, dict):
            secret = {}

        supplier_id = str(scope.get("supplier_id") or "approved-provider-probe")
        supplier_name = "Approved Provider Probe"
        program_refs = scope.get("program_refs") or ["approved-provider"]
        program_ref = str(program_refs[0] if isinstance(program_refs, list) and program_refs else "approved-provider")
        program_id = f"program:{_hash_text(program_ref)}"
        domain = _clean_domain(row.get("host") or scope.get("query_value"))

        exp_id = f"exp:live:{source_hash}"
        identity_id = f"id:live:{source_hash}"
        device_id = f"dev:live:{source_hash}"
        source_id = f"src:stealthmole:{module}:{source_hash}"
        active = bool(row.get("is_active_signal"))

        module_counts[module] += 1
        host_counts[domain] += 1
        active_count += int(active)

        suppliers.append(
            {
                "id": supplier_id,
                "name": supplier_name,
                "tier": 0,
                "criticality": "unknown",
                "status": "provider_probe",
                "is_prime_candidate": "false",
            }
        )
        programs.append(
            {
                "id": program_id,
                "name": f"Provider measurement scope {program_ref}",
                "sensitivity": "measurement",
                "status": "measurement",
            }
        )
        domains.append(
            {
                "fqdn": domain,
                "host": domain,
                "url": f"https://{domain}",
                "asset_type": "provider_observed_domain",
                "criticality": "unknown",
                "access_surface": "approved_provider_query",
                "verified_at": _iso(row.get("observed_at") or row.get("fetched_at")),
            }
        )
        identities.append(
            {
                "id": identity_id,
                "email": "",
                "username": "",
                "canonical_handle": f"hashed:{source_hash}",
                "account_type": str(device.get("account_type") or "unknown"),
                "status": "provider_observed",
                "merged_into": "",
            }
        )
        credential_exposures.append(
            {
                "id": exp_id,
                "module": module,
                "secret_type": str(secret.get("type") or "unknown"),
                "secret_present": str(bool(secret.get("present"))).lower(),
                "masked_value": str(secret.get("masked_value") or f"redacted:{source_hash}"),
                "secret_fingerprint": f"fp:live:{_hash_text(exp_id)}",
                "first_seen": _iso(row.get("observed_at")),
                "last_seen": _iso(row.get("fetched_at") or row.get("observed_at")),
                "source_ref": source_id,
                "confidence": row.get("confidence") or 0,
                "status": "active_candidate" if active else "observed",
            }
        )
        infected_devices.append(
            {
                "id": device_id,
                "device_fingerprint": f"dfp:live:{source_hash}",
                "malware": str(device.get("malware") or "unknown"),
                "infected_at": _iso(device.get("infected_at")),
                "has_session_cookie": str(bool(device.get("has_session_cookie"))).lower(),
                "os": str(device.get("os") or "unknown"),
                "status": "active_candidate" if active else "observed",
            }
        )
        threat_sources.append(
            {
                "id": source_id,
                "kind": f"stealthmole_{module}",
                "name": f"StealthMole {module.upper()} approved hackathon row {source_hash}",
                "collected_at": _iso(row.get("fetched_at") or row.get("observed_at")),
                "reliability": row.get("confidence") or 0,
                "status": "approved_filtered",
            }
        )
        link_owns.append({"left-Supplier-primary-key": supplier_id, "right-Domain-primary-key": domain})
        link_belongs_to.append({"left-Identity-primary-key": identity_id, "right-Domain-primary-key": domain})
        link_of.append({"left-CredentialExposure-primary-key": exp_id, "right-Identity-primary-key": identity_id})
        link_targets.append({"left-CredentialExposure-primary-key": exp_id, "right-Domain-primary-key": domain})
        link_sourced_from.append(
            {"left-CredentialExposure-primary-key": exp_id, "right-ThreatSource-primary-key": source_id}
        )
        link_leaked.append(
            {"left-InfectedDevice-primary-key": device_id, "right-CredentialExposure-primary-key": exp_id}
        )
        link_compromises.append({"left-InfectedDevice-primary-key": device_id, "right-Identity-primary-key": identity_id})

    files = {
        "01_supplier.csv": _dedupe(suppliers, "id"),
        "03_program.csv": _dedupe(programs, "id"),
        "04_domain.csv": _dedupe(domains, "fqdn"),
        "05_identity.csv": _dedupe(identities, "id"),
        "06_credential_exposure.csv": _dedupe(credential_exposures, "id"),
        "07_infected_device.csv": _dedupe(infected_devices, "id"),
        "08_threat_source.csv": _dedupe(threat_sources, "id"),
        "23_link_owns.csv": _dedupe(link_owns, "right-Domain-primary-key"),
        "25_link_belongs_to.csv": _dedupe(link_belongs_to, "left-Identity-primary-key"),
        "26_link_of.csv": _dedupe(link_of, "left-CredentialExposure-primary-key"),
        "27_link_targets.csv": _dedupe(link_targets, "left-CredentialExposure-primary-key"),
        "28_link_sourced_from.csv": _dedupe(link_sourced_from, "left-CredentialExposure-primary-key"),
        "29_link_leaked.csv": _dedupe(link_leaked, "right-CredentialExposure-primary-key"),
        "30_link_compromises.csv": _dedupe(link_compromises, "left-InfectedDevice-primary-key"),
    }

    return {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "source": str(INPUT_JSON.relative_to(REPO_ROOT)),
        "policy": {
            "input_private": True,
            "raw_provider_payload_exported": False,
            "api_secret_exported": False,
            "raw_email_exported": False,
            "raw_secret_material_exported": False,
            "identity_strategy": "source_ref_hash",
        },
        "summary": {
            "input_records": len(exposures),
            "modules": dict(sorted(module_counts.items())),
            "active_candidates": active_count,
            "unique_domains": len(host_counts),
            "foundry_object_rows": {
                "Supplier": len(files["01_supplier.csv"]),
                "Program": len(files["03_program.csv"]),
                "Domain": len(files["04_domain.csv"]),
                "Identity": len(files["05_identity.csv"]),
                "CredentialExposure": len(files["06_credential_exposure.csv"]),
                "InfectedDevice": len(files["07_infected_device.csv"]),
                "ThreatSource": len(files["08_threat_source.csv"]),
            },
            "foundry_link_rows": {
                name.removesuffix(".csv"): len(rows)
                for name, rows in files.items()
                if name.startswith(("23_", "25_", "26_", "27_", "28_", "29_", "30_"))
            },
            "derived_decision_objects": 0,
            "derived_decision_reason": "approved provider probe has no confirmed defense supplier path; do not create Incident/Draft without provenance",
        },
        "top_domains": host_counts.most_common(10),
        "files": {name: len(rows) for name, rows in files.items()},
        "_csv_rows": files,
    }


def render_markdown(measurement: dict[str, Any]) -> str:
    summary = measurement["summary"]
    files = "\n".join(f"- `{name}`: `{count}` rows" for name, count in sorted(measurement["files"].items()))
    modules = "\n".join(f"- `{name}`: `{count}` records" for name, count in summary["modules"].items())
    return f"""# Foundry Live Measurement Bundle

Generated: `{measurement['generated_at']}`

This bundle converts approved filtered StealthMole hackathon rows into Foundry-ready
ontology CSVs. It intentionally excludes raw provider envelopes, API secrets, JWTs,
raw emails, passwords, cookies, and tokens.

## Summary

- Input records: `{summary['input_records']}`
- Active candidates: `{summary['active_candidates']}`
- Unique observed domains: `{summary['unique_domains']}`
- Derived decision objects: `{summary['derived_decision_objects']}`
- Decision reason: {summary['derived_decision_reason']}

## Modules

{modules}

## Generated Files

{files}

## Foundry Load Order

1. Object CSVs: `01`, `03`, `04`, `05`, `06`, `07`, `08`.
2. Link CSVs: `23`, `25`, `26`, `27`, `28`, `29`, `30`.
3. Re-index ontology object/link types.
4. Measure object counts and path readback against `measurement.json`.
"""


def _optional_json(path: Path) -> dict[str, Any]:
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return {}
    return data if isinstance(data, dict) else {}


def render_html(measurement: dict[str, Any]) -> str:
    summary = measurement["summary"]
    upload = _optional_json(OUT_DIR / "upload_result.json")
    readback = _optional_json(OUT_DIR / "readback_result.json")
    schema_put = _optional_json(OUT_DIR / "schema_put_result.json")
    sql_measurement = _optional_json(OUT_DIR / "sql_measurement_result.json")
    file_rows = "\n".join(
        f"<tr><td>{name}</td><td>{count}</td></tr>" for name, count in sorted(measurement["files"].items())
    )
    module_rows = "\n".join(f"<tr><td>{name.upper()}</td><td>{count}</td></tr>" for name, count in summary["modules"].items())
    sql_rows = "\n".join(
        f"<tr><td>{row.get('name')}</td><td>{row.get('sql_count')}</td><td>{row.get('rows_expected')}</td><td>{'OK' if row.get('ok') else 'CHECK'}</td></tr>"
        for row in sql_measurement.get("results", [])
    )
    upload_ok = sum(1 for row in upload.get("results", []) if row.get("ok"))
    upload_total = len(upload.get("results", []))
    schema_ok = schema_put.get("ok_count", 0)
    schema_total = schema_put.get("target_count", 0)
    sql_ok = sql_measurement.get("ok_count", 0)
    sql_total = sql_measurement.get("target_count", 0)
    readback_ok = bool(readback.get("ok"))
    return f"""<!doctype html>
<html lang="ko">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Omija Foundry Live Measurement</title>
<style>
:root {{ color-scheme: dark; --bg:#0b0c0d; --panel:#151719; --line:#333942; --ink:#f2f4f8; --muted:#aeb7c2; --good:#2ea043; --warn:#f0b73f; --bad:#f85149; }}
* {{ box-sizing:border-box; }}
body {{ margin:0; background:var(--bg); color:var(--ink); font:14px/1.5 system-ui,-apple-system,Segoe UI,sans-serif; }}
header,main {{ max-width:1040px; margin:0 auto; padding:22px; }}
h1 {{ margin:0 0 8px; font-size:26px; letter-spacing:0; }}
p {{ color:var(--muted); margin:0; }}
.grid {{ display:grid; grid-template-columns:repeat(4,minmax(0,1fr)); gap:12px; margin:18px 0; }}
.card {{ border:1px solid var(--line); border-radius:8px; background:var(--panel); padding:14px; }}
.k {{ color:var(--muted); font:11px ui-monospace,SFMono-Regular,Menlo,monospace; text-transform:uppercase; letter-spacing:.9px; }}
.v {{ margin-top:6px; font:24px ui-monospace,SFMono-Regular,Menlo,monospace; }}
.ok {{ color:var(--good); }} .warn {{ color:var(--warn); }}
table {{ width:100%; border-collapse:collapse; margin-top:10px; }}
td,th {{ border-top:1px solid var(--line); padding:7px 8px; text-align:left; font-size:12px; }}
th {{ color:var(--muted); font:10px ui-monospace,SFMono-Regular,Menlo,monospace; text-transform:uppercase; }}
section {{ border:1px solid var(--line); border-radius:8px; background:var(--panel); padding:14px; margin:14px 0; }}
@media(max-width:760px) {{ .grid {{ grid-template-columns:1fr 1fr; }} }}
@media(max-width:460px) {{ .grid {{ grid-template-columns:1fr; }} header,main {{ padding:16px; }} }}
</style>
</head>
<body>
<header>
  <div class="k">OMIJA · FOUNDRY LIVE MEASUREMENT</div>
  <h1>승인된 StealthMole row → Foundry-ready ontology measurement</h1>
  <p>Raw provider envelope, raw email, API secret, JWT, password, cookie, token are not exported.</p>
</header>
<main>
  <div class="grid">
    <div class="card"><div class="k">Provider rows</div><div class="v">{summary['input_records']}</div></div>
    <div class="card"><div class="k">CredentialExposure</div><div class="v">{summary['foundry_object_rows']['CredentialExposure']}</div></div>
    <div class="card"><div class="k">ThreatSource</div><div class="v">{summary['foundry_object_rows']['ThreatSource']}</div></div>
      <div class="card"><div class="k">Schema PUT</div><div class="v {'ok' if schema_ok == schema_total and schema_total else 'warn'}">{schema_ok}/{schema_total}</div></div>
      <div class="card"><div class="k">SQL Counts</div><div class="v {'ok' if sql_ok == sql_total and sql_total else 'warn'}">{sql_ok}/{sql_total}</div></div>
      <div class="card"><div class="k">Ontology Readback</div><div class="v {'ok' if readback_ok else 'warn'}">{'OK' if readback_ok else 'NOT_INDEXED'}</div></div>
  </div>
  <section>
    <h2>Module Counts</h2>
    <table><thead><tr><th>module</th><th>records</th></tr></thead><tbody>{module_rows}</tbody></table>
  </section>
  <section>
    <h2>Generated Foundry CSVs</h2>
    <table><thead><tr><th>file</th><th>rows</th></tr></thead><tbody>{file_rows}</tbody></table>
  </section>
    <section>
      <h2>Foundry Upload / Readback</h2>
      <p>Backing dataset uploads: <b>{upload_ok}/{upload_total}</b>. Explicit schemas: <b>{schema_ok}/{schema_total}</b>. OSDK object readback: <b>{'ok' if readback_ok else 'not indexed yet'}</b>.</p>
      <p>Artifacts: <code>upload_result.json</code>, <code>schema_put_result.json</code>, <code>readback_result.json</code>.</p>
    </section>
    <section>
      <h2>Foundry SQL Counts</h2>
      <p>Separate schema-aware live measurement datasets were created from the same sanitized CSVs so judges can see real approved provider rows measured in Foundry while ontology datasource indexing is refreshed.</p>
      <table><thead><tr><th>dataset</th><th>sql count</th><th>expected</th><th>status</th></tr></thead><tbody>{sql_rows}</tbody></table>
      <p>Artifact: <code>sql_measurement_result.json</code>.</p>
    </section>
</main>
</body>
</html>"""


def _safety_check(path: Path) -> None:
    text = "\n".join(p.read_text(encoding="utf-8") for p in path.glob("*") if p.is_file())
    problems: list[str] = []
    if EMAIL_RE.search(text):
        problems.append("raw email pattern")
    if FORBIDDEN_RE.search(text):
        problems.append("token/API-key pattern")
    lowered = text.lower()
    for forbidden in ("raw_password", "raw_cookie", "raw_token"):
        if forbidden in lowered:
            problems.append(forbidden)
    if problems:
        raise RuntimeError("unsafe foundry measurement output: " + ", ".join(sorted(set(problems))))


def run() -> int:
    data = _read_json(INPUT_JSON)
    measurement = build(data)
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    for old in OUT_DIR.glob("*"):
        if old.is_file() and (old.suffix == ".csv" or old.name in {"measurement.json", "measurement.md", "measurement.html"}):
            old.unlink()
    csv_rows = measurement.pop("_csv_rows")
    for name, rows in csv_rows.items():
        _write_csv(name, rows)
    OUT_JSON.write_text(json.dumps(measurement, indent=2, ensure_ascii=False), encoding="utf-8")
    OUT_MD.write_text(render_markdown(measurement), encoding="utf-8")
    html = render_html(measurement)
    OUT_HTML.write_text(html, encoding="utf-8")
    PUBLIC_HTML.write_text(html, encoding="utf-8")
    _safety_check(OUT_DIR)
    print(f"wrote {OUT_DIR.relative_to(REPO_ROOT)} records={measurement['summary']['input_records']}")
    print("RESULT: OK")
    return 0


if __name__ == "__main__":
    raise SystemExit(run())
